name: Developer Sandbox Org

on:
  workflow_dispatch:

jobs:
  Build:
    name: environment-setup
    runs-on: ubuntu-latest
    steps:
      # Checkout the Source code from the latest commit
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install the SFDX CLI
        run: |
          npm install @salesforce/cli --global
          sf --help
      - name: Decrypt the server.key.enc file & store inside assets folder
        run: |
          openssl enc -nosalt -aes-256-cbc -d -in ${{ secrets.ENCRYPTION_KEY_FILE }} -out ${{ secrets.SALESFORCE_JWT_KEY }} -base64 -K ${{ secrets.DECRYPTION_KEY }} -iv ${{ secrets.DECRYPTION_IV }}

      - name: Authenticate Salesforce ORG
        run: |
          sf org login jwt --client-id ${{ secrets.SALESFORCE_CONSUMER_KEY_PAWANDEV }} --jwt-key-file  ${{ secrets.SALESFORCE_JWT_KEY }} --username ${{ secrets.SALESFORCE_USERNAME_PAWANDEV }} --set-default --alias HubOrg --instance-url ${{ secrets.SFDX_AUTH_URL_SANDBOX }}

      - name: Validate components to Salesforce
        run: |
          sf project deploy validate --manifest delta/package/package.xml --test-level RunLocalTests --target-org HubOrg --coverage-formatters clover

      - name: Deploy Delta components to Salesforce
        run: |
          sf project deploy start --manifest delta/package/package.xml --test-level RunLocalTests --target-org HubOrg --coverage-formatters clover
